### PR TITLE
Add openstack_auth() helper

### PR DESCRIPTION
**Pull request by gandelman-a**
This adds an openstack_auth() helper function to construct an appropriate
keystone auth dict to be used /w shade.  This can be expanded to include
auth plugins other than password as they become supported elsewhere.

### CODE REVIEW

**Comment by gandelman-a** [comment]
i'll probably just keep stacking anything needed for the ansible module work here. consider this a working branch for now

**Comment by Shrews** [comment]
I thought that with the recent session changes, other plugins are already automatically supported just by setting 'auth_plugin' and the proper values in 'auth'? This proposed change forces us to know what the other plugins are and what values they need.

**Comment by gandelman-a** [comment]
Yeah, and this sets 'auth_plugin' and proper values in 'auth' for the password auth.  Without doing so, the module ends up trying to setup a session with auth_plugin='password' and auth={}

**Comment by Shrews** [comment]
Ah, so, I think the issue you're having is that the format of the YAML for os-client-config has changed in 0.4.0. Now, these parameters must be defined in an 'auth' section. See the examples in the latest README:

https://review.openstack.org/gitweb?p=stackforge/os-client-config.git;a=blob;f=README.rst;h=e6dbed07276afd995c00541919313f62401aee0e;hb=HEAD

**Comment by gandelman-a** [comment]
Yes, but we're not using a yaml config here, instead those values come from the ansible module parameters and the auth dict needs to be constructed somewhere.

**Comment by emonty** [comment]
After a conversation in #openstack-infra - we decided that we'd just keep the auth dict structure for consistency.

**Pull request closed without merging**
